[theme]
primaryColor = "#0365C0"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1f4e79"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
